---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: binddns-sa
  namespace: default

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: binddns-role
rules:
  - apiGroups: ["binddns.github.com"]
    resources: ["dnsdomains", "dnsrules", "dnsdomains/status", "dnsrules/status"]
    verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: binddns-rolebinding
subjects:
  - kind: ServiceAccount
    name: binddns-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: binddns-role
  apiGroup: rbac.authorization.k8s.io
